### ISSUE TITLE
"file exists" error if folder is added to data-files

### ISSUE THREAD

**Issue by nilskuhn** [UrbanMachine/colcon-poetry-ros#33]
The README points out, _that that copying entire directories is supported_ for data files. 

If I use something like this:
```
[tool.colcon-poetry-ros.data-files]
"share/ament_index/resource_index/packages" = ["resource/{package_name}"]
"share/{package_name}" = ["package.xml", "secrets"]
```
The first build runs fine and _secrets_ folder is copied to share folder correctly. But from the second build on, I do get the following error:
```
--- stderr: {package_name}                   
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/colcon_poetry_ros/task/poetry/build.py", line 133, in build
    return_code = await self._add_data_files()
  File "/usr/local/lib/python3.8/dist-packages/colcon_poetry_ros/task/poetry/build.py", line 209, in _add_data_files
    shutil.copytree(str(source_path), str(dest_path / source_path.name))
  File "/usr/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.8/shutil.py", line 458, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/path/to/my/ros2/ws/install/{package_name}/share/{package_name}/secrets'
```
Thanks in advance, regards, Nils

**Comment by velovix** [comment]
Thank you for the report! There should be a fix in soon.
