### ISSUE TITLE
Exception when building a projct

### ISSUE THREAD

**Issue by apockill** [UrbanMachine/colcon-poetry-ros#9]
This may be caused after adding python files to a package or adding a dependency. Exact replication instructions haven't been determined yet. 

```bash
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/colcon_poetry_ros/task/poetry/build.py", line 101, in build
    shutil.copy2(str(script), str(ros_script_dir))
  File "/usr/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/robot/install/vision/bin/__pycache__'
```

**Comment by velovix** [comment]
Fixed by afb89c24f2cad2e785d69986877b426bc0c2117c
